async (page) => {
  await page.getByLabel('想做什么').fill('测试：读一课 <script>');
  await page.getByLabel('任务类型', {exact:true}).fill('比赛');
  await page.getByLabel('选择颜色 #5684ad', {exact:true}).click();
  await page.getByLabel('开始时间（可留空）', {exact:true}).fill('22:00');
  await page.getByLabel('结束时间（可留空）', {exact:true}).fill('21:00');
  await page.getByRole('button', {name:'保存日程',exact:true}).click();
  if (!(await page.locator('#form-error').innerText()).includes('结束时间')) throw Error('invalid time accepted');
  await page.getByLabel('结束时间（可留空）', {exact:true}).fill('23:00');
  await page.getByLabel('第一步 / 留给自己的话').fill('打开文档，写下一个问题。');
  await page.getByRole('button', {name:'保存日程',exact:true}).click();
  await page.locator('#editor').waitFor({state:'hidden'});
  const task=page.locator('.task').filter({hasText:'测试：读一课 <script>'});
  await task.waitFor();
  if (!(await task.getAttribute('style')).includes('#5684ad')) throw Error('color not saved');
  await task.getByRole('button', {name:'开始这件事'}).click();
  await page.waitForFunction(() => document.querySelector('.task.running')?.textContent.includes('测试：读一课'));
  await task.getByRole('button', {name:'暂停',exact:true}).click();
  await page.waitForFunction(() => !document.querySelector('.task.running'));
  await task.getByRole('button', {name:'完成：测试：读一课 <script>',exact:true}).click();
  await page.waitForFunction(() => [...document.querySelectorAll('.task.done')].some(t=>t.textContent.includes('测试：读一课')));
  await page.reload();
  await page.getByRole('heading', {name:'测试：读一课 <script>',exact:true}).waitFor();
  if (await page.locator('.task script').count()) throw Error('HTML injection');
  const response=await page.request.get('http://127.0.0.1:18766/api/calendar?date=2026-09-06');
  const ics=await response.text();
  if (!ics.includes('DTSTART:20260906T140000Z') || ics.includes('SUMMARY:独立站')) throw Error('calendar content invalid');
  await page.getByRole('button', {name:'加入日历',exact:true}).click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button', {name:/下载 .ics 文件/}).click();
  const download=await downloadPromise;
  if (!download.suggestedFilename().endsWith('.ics')) throw Error('calendar download missing');
  await page.locator('#close-calendar').click();
  await page.getByRole('button', {name:'后一天',exact:true}).click();
  await page.getByRole('heading', {name:'这一天，还可以慢慢安排。'}).waitFor();
  await page.getByRole('button', {name:'今天',exact:true}).click();
  await page.getByRole('heading', {name:'测试：读一课 <script>',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if (overflow) throw Error('mobile horizontal overflow');
  await page.screenshot({path:'.playwright-cli/daaaay-mobile.png',fullPage:true});
  console.log('PASS: validation, colors, start/pause/complete, persistence, escaping, ICS, navigation and mobile width');
}
